.TH studio-system 2 "16 June 2018" "version 2.0"
.SH NAME
studio-system \- The system end of studio-controls
.SH SYNOPSIS
.BI "studio-system " "command"
.SH DESCRIPTION
Studio-system is the system half of studio-controls. It runs
commands as system that the gui requires. Only one command can be sent at
a time. The commands are effective over reboot.
.LP
Security is ensured by not taking any random text as options or commands.
Rather commands are limited to those listed.
.SH COMMANDS
.B fix
- Fixes rt permissions for the user running studio-controls
.LP
.B boost
- Turns CPU BOOST on
.LP
.B noboost
- Turns CPU BOOST off
.LP
.B powersave
- Sets CPU governor to powersave
.LP
.B ondemand
- Sets CPU governor to ondemand or powersave if ondemand is not supported
.LP
.B performance
- Sets CPU Governor to performance
.SH OPTIONS
studio-system does not take any options.
.SH SEE ALSO
studio-controls(1), studio-cmd(1), autojack(2)
.SH BUGS
No known bugs.
.SH AUTHOR
Len Ovens (len@ovenwerks.net)
