.TH ubuntustudio-system 2 "16 June 2018" "version 1.5"
.SH NAME
ubuntustudio-system \- The system end of ubuntustudio-controls
.SH SYNOPSIS
.BI "ubuntustudio-system " "command"
.SH DESCRIPTION
Ubuntustudio-system is the system half of ubuntustudio-controls. It runs
commands as system that the gui requires. Only one command can be sent at
a time. The commands are effective over reboot.
.LP
Security is ensured by not taking any random text as options or commands.
Rather commands are limited to those listed.
.SH COMMANDS
.B fix
- Fixes rt permissions for the user running ubuntustudio-controls
.LP
.B boost
- Turns CPU BOOST on
.LP
.B noboost
- Turns CPU BOOST off
.LP
.B powersave
- Sets CPU governor to powersave
.LP
.B ondemand
- Sets CPU governor to ondemand or powersave if ondemand is not supported
.LP
.B performance
- Sets CPU Governor to performance
.SH OPTIONS
ubuntustudio-system does not take any options.
.SH SEE ALSO
ubuntustudio-controls(1), autojack(2)
.SH BUGS
No known bugs.
.SH AUTHOR
Len Ovens (len@ubuntustudio.org)
