#!/bin/sh
### BEGIN INIT INFO
# Provides:       ubuntustudio
# Required-Start: $remote_fs $all
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:
# Short-Description: Various boot time settings for audio
# Description: Boot time settings for boost, other stuff coming
### END INIT INFO
# 

DESC="Ubuntustudio Controls"

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#CPUFREQ_SET=/usr/bin/cpufreq-set
#CPUFREQ_INFO=/usr/bin/cpufreq-info
#CPUFREQ_OPTIONS=""

# use lsb-base
#. /lib/lsb/init-functions

# these are defaults. They should be set to what a normal
#	non-audio system has.
# Set ENABLE to "true" to let the script run at boot time.
# 
# eg:	ENABLE="true"
#	GOVERNOR="ondemand"
#	MAX_SPEED=1000
#	MIN_SPEED=500

ENABLE="true"
NO_TURBO="0"

# we should check for the availablity of any setting we wish to change
check_turbo_avail() {
	info="/sys/devices/system/cpu/intel_pstate/no_turbo"
	if [ -f $info ]; then
		return 0;
	fi
	return 1;
}

# check for execucables we need
#[ -x $CPUFREQ_SET ] || exit 0

# any setting in this file will override the above defaults.
# ubuntustudio-controls will normally write the defaults file
if [ -f /etc/default/ubuntustudio ] ; then
	. /etc/default/ubuntustudio
fi

# if not enabled then exit gracefully
[ "$ENABLE" = "true" ] || exit 0

#CPUS=$(cat /proc/stat|sed -ne 's/^cpu\([[:digit:]]\+\).*/\1/p')
RETVAL=0
case "$1" in
	start|force-reload|restart|reload)
# real stuff happens here
		logger "$DESC: Setting system settings"
		if check_turbo_avail ; then
			logger "Set no_turbo $NO_TURBO"
			echo "${NO_TURBO}" | tee /sys/devices/system/cpu/intel_pstate/no_turbo || \
				RETVAL=$?
#			done
			logger "$DESC: $RETVAL "
		else
			log_action_cont_msg "turbo/boost not available"
			log_action_end_msg $RETVAL
		fi
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}"
		exit 1
esac

exit 0

