#! /bin/sh
#
# Script to change do system side things for studio-controls
#
#
GOVERNOR="ondemand"
NO_TURBO="0"

set_governors() {
	AVAILABLE="/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors"
	[ -f $AVAILABLE ] || exit 0
	read governors < $AVAILABLE
	case "$GOVERNOR" in
		performance)
			case $governors in
				*performance*)
					GOVERNOR="performance"
					;;
				*)
					exit 0
					;;
			esac
			;;
		*)
			case $governors in
				*ondemand*)
					GOVERNOR="ondemand"
					;;
				*powersave*)
					GOVERNOR="powersave"
					;;
				*)
					exit 0
					;;
			esac
			;;
	esac

	for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
		do
			[ -f $CPUFREQ ] || continue
			echo -n $GOVERNOR > $CPUFREQ
		done
}

# we don't use this any more
if [ -f /etc/default/studio ] ; then
	rm /etc/default/studio
fi

case "$1" in
	performance)
		GOVERNOR="performance"
		set_governors
		;;

	ondemand)
		GOVERNOR="ondemand"
		set_governors
		;;

	powersave)
		GOVERNOR="powersave"
		set_governors
		;;

	fix)
		if [ -f /etc/security/limits.d/audio.conf.disabled ]; then
			mv /etc/security/limits.d/audio.conf.disabled /etc/security/limits.d/audio.conf
		elif ! [ -f /etc/security/limits.d/audio.conf ]; then
			cp /usr/share/studio-controls/audio.conf /etc/security/limits.d/audio.conf
		fi
		if [ ${PKEXEC_UID} -gt 999 ]; then
			/usr/sbin/usermod `id -nu ${PKEXEC_UID}` -aG audio
		fi
		;;

	boost)
		if [ -f /sys/devices/system/cpu/intel_pstate/no_turbo ]; then
			echo "0" | tee /sys/devices/system/cpu/intel_pstate/no_turbo
		fi
		;;

	noboost)
		if [ -f /sys/devices/system/cpu/intel_pstate/no_turbo ]; then
			echo "1" | tee /sys/devices/system/cpu/intel_pstate/no_turbo
		fi
		;;


	nosys)
        # TODO test for file or systemd service
		/etc/init.d/cron stop
		;;

	sys)
        # TODO test for file or systemd service
		/etc/init.d/cron start
		;;

	ffado)
		if ! [ -f /etc/modprobe.d/blacklist-studio.conf ]; then
			cp /usr/share/studio-controls/blacklist-studio.conf /etc/modprobe.d/blacklist-studio.conf
		fi
		;;

	alsa)
		if [ -f /etc/modprobe.d/blacklist-studio.conf ]; then
			rm /etc/modprobe.d/blacklist-studio.conf
		fi
		;;

	jacklib)
		# do stuff to point calls to jacklib at real jack
        rm /etc/ld.so.conf.d/pipewire-jack*.conf
        ldconfig
		exit 0
		;;

	pwlib)
		# do stuff to point calls to jacklib at pipewire
        if ! [ -f /etc/ld.so.conf.d/pipewire-jack-x86_64-linux-gnu.conf ]; then
            # We create the file on the fly because path may change with
            # version
            ls -d /usr/lib/*/pipewire*/jack/ > \
            /etc/ld.so.conf.d/pipewire-jack.conf
            #cp -f /usr/share/studio-controls/pipewire-jack-x86_64-linux-gnu.conf \
            #/etc/ld.so.conf.d/
            ldconfig
        fi
		exit 0
		;;

	*)
		exit 0
		;;

	esac
