.TH ubuntustudio-controls 1 "Jan 20, 2008" "Ubuntu Studio Devel"

.SH NAME
.B ubuntustudio-controls
 - a small app for editing settings on audio, video and graphics workstations
.SH SYNOPSIS
.B ubuntustudio-controls
.SH DESCRIPTION
.B ubuntustudio-controls
is a small app that provides users access to commonly hand-edited settings on an A/V production system.
.SH SEE ALSO
See https://wiki.ubuntu.com/UbuntuStudio/SettingsApp for more information.
.SH AUTHOR
This manpage was written by Andrew Hunter <andrew@aehunter.net>.
