.TH studio-controls 1 "16 June 2018" "version 2.0"
.SH NAME
studio-controls \- Is an audio setup utility for sound studio use
.SH SYNOPSIS
studio-controls
.SH DESCRIPTION
Studio-controls is an audio setup utility. It has a GUI that first
checks that the user has correct real time permissions to run professional
audio applications. The user is warned if real time permissions are not
correct and if the user desires, corrects permissions. The user will be
asked to log out and back in so these permissions can take effect.
.LP
The running of jackdbus and extra utilities is also set up with
studio-controls. Along with jackdbus itself, extra audio devices
can be set up as jack clients, USB devices can become jack master when
plugged in or added as jack clients. A2jmidid can be started to bridge
ALSA MIDI devices and applications to jack. Pulseaudio can be bridged
and connected to the right outputs of an output device.
.LP
Studio-controls tries to be non-invasive and when jack is turned off
the system should run normally using Pulseaudio for sound.
.SH OPTIONS
Studio-controls does not take any options.
.SH SEE ALSO
studio-cmd(1), autojack(2), studio-system(2)
.SH BUGS
No known bugs.
.SH AUTHOR
Len Ovens (len@ovenwerks.net)
